Repository systopia/civiremote, pull requests merged in 2023-11, with the labels that each got.

#10 WIP: Add generic CiviCRM entity implementation
  .github/workflows/phpcs_entity.yml
  .github/workflows/phpstan_entity.yml
  .gitignore
  composer.json
  modules/civiremote_entity/ci/README.md
  modules/civiremote_entity/ci/composer.json
  modules/civiremote_entity/civiremote_entity.info.yml
  modules/civiremote_entity/civiremote_entity.services.yml
  modules/civiremote_entity/composer.json
  modules/civiremote_entity/phpcs.xml.dist
  modules/civiremote_entity/phpstan.ci.neon
  modules/civiremote_entity/phpstan.neon.dist
  modules/civiremote_entity/phpunit.xml.dist
  modules/civiremote_entity/src/Access/RemoteContactIdProvider.php
  modules/civiremote_entity/src/Access/RemoteContactIdProviderInterface.php
  modules/civiremote_entity/src/Api/AbstractEntityApi.php
  modules/civiremote_entity/src/Api/CiviCRMApiClient.php
  modules/civiremote_entity/src/Api/CiviCRMApiClientInterface.php
  modules/civiremote_entity/src/Api/Exception/ApiCallFailedException.php
  modules/civiremote_entity/src/Api/Exception/ExceptionInterface.php
  modules/civiremote_entity/src/Api/Form/EntityForm.php
  modules/civiremote_entity/src/Api/Form/FormSubmitResponse.php
  modules/civiremote_entity/src/Api/Form/FormValidationResponse.php
  modules/civiremote_entity/src/Form/AbstractEntityForm.php
  modules/civiremote_entity/src/Form/RequestHandler/EntityCreateFormRequestHandler.php
  modules/civiremote_entity/src/Form/RequestHandler/EntityUpdateFormRequestHandler.php
  modules/civiremote_entity/src/Form/RequestHandler/FormRequestHandlerInterface.php
  modules/civiremote_entity/src/Form/ResponseHandler/FormResponseHandlerChain.php
  modules/civiremote_entity/src/Form/ResponseHandler/FormResponseHandlerInterface.php
  modules/civiremote_entity/src/Form/ResponseHandler/FormResponseHandlerMessage.php
  modules/civiremote_entity/tools/phpstan/composer.json
Labels: enhancement

#11 WIP: Add implementation for CiviCRM Activity entities
  .github/workflows/phpcs_activity.yml
  .github/workflows/phpstan_activity.yml
  modules/civiremote_activity/ci/README.md
  modules/civiremote_activity/ci/composer.json
  modules/civiremote_activity/civiremote_activity.info.yml
  modules/civiremote_activity/civiremote_activity.routing.yml
  modules/civiremote_activity/civiremote_activity.services.yml
  modules/civiremote_activity/composer.json
  modules/civiremote_activity/phpcs.xml.dist
  modules/civiremote_activity/phpstan.ci.neon
  modules/civiremote_activity/phpstan.neon.dist
  modules/civiremote_activity/phpunit.xml.dist
  modules/civiremote_activity/src/Api/ActivityApi.php
  modules/civiremote_activity/src/Controller/ActivityCreateController.php
  modules/civiremote_activity/src/Controller/ActivityUpdateController.php
  modules/civiremote_activity/src/Form/ActivityCreateForm.php
  modules/civiremote_activity/src/Form/ActivityUpdateForm.php
  modules/civiremote_activity/src/Form/RequestHandler/ActivityCreateFormRequestHandler.php
  modules/civiremote_activity/src/Form/RequestHandler/ActivityUpdateFormRequestHandler.php
  modules/civiremote_activity/tools/phpstan/composer.json
Labels: enhancement

#12 Retrieve cancellation form also when not using tokens
  modules/civiremote_event/src/Form/RegistrationCancelForm.php
Labels: bug, status:reviewed and tested

#13 Allow markup in messages
  src/Utils.php
Labels: enhancement

#18 Implement "Add more" functionality for additional participants' fields
  modules/civiremote_event/src/Form/RegisterForm.php
Labels: enhancement, status:needs review
