Repository systopia/civiremote, pull requests merged in 2024-02, with the labels that each got.

#21 Throw exception when dependent field can not be found in form definition
  modules/civiremote_event/src/Form/RegisterForm.php
Labels: status:reviewed and tested

#20 Require `drupal/cmrf_core` 2.1 for APIv4 compatibility
  composer.json
  modules/civiremote_activity/ci/composer.json
  modules/civiremote_entity/ci/composer.json
  modules/civiremote_entity/composer.json
Labels: enhancement, status:reviewed and tested

#22 Allow profile parameter for token-based forms
  modules/civiremote_event/civiremote_event.routing.yml
  modules/civiremote_event/src/Controller/RegisterFormController.php
Labels: status:needs review

#23 Allow arrays as default value for checkboxes elements
  modules/civiremote_event/src/Form/RegisterForm.php
Labels: bug, status:reviewed and tested

#24 Use form ID depending on route context
  modules/civiremote_event/src/Controller/RegisterFormController.php
Labels: bug, status:needs review
