Repository systopia/civiremote, pull requests merged in 2024-10, with the labels that each got.

#38 Use correct translation placeholder syntax for error messages
  modules/civiremote_entity/src/CiviCRMPage/CiviCRMPageProxy.php
Labels: bug, status:needs review

#34 Add configuration option for whether to match blocked users (defaulting to FALSE)
  config/install/civiremote.settings.yml
  config/schema/civiremote.schema.yml
  src/Form/CiviRemoteConfigForm.php
  src/User.php
  translations/civiremote.pot
  translations/de.po
Labels: enhancement, status:needs review

#39 FileArrayFactory: Allow default value to be array
  modules/civiremote_entity/src/Form/Control/FileArrayFactory.php
Labels: bug
